#!/bin/bash

# NOTICE:
# Insert this script to crontab with "/bin/bash -l -c 'transmission-start'" command
# because auth login and password set in variable in ~/.bash_profile

# This hosts should be offline when start transmission
IMPORTANT_ADDRESS="192.168.1.3 192.168.1.4 192.168.1.5"
TRANS_REMOTE="/usr/bin/transmission-remote"
DEFAULT_OPT="-ne"

# Ping command
function ping_command(){
    ping -c 2 -w 2 "$1" -q &>/dev/null
}

# Check live hosts by ping
function check_live_hosts {
    for i in $IMPORTANT_ADDRESS; do 
        if ping_command $i ; then
            return 0
        fi
    done
    return 1
}

# Checkk ssh connections, only by connected ezo user
function check_ssh {
    if [ -n "$(ps aux|grep ssh|grep 'sshd: ezo'|grep -v grep)" ]; then return 0; fi
    return 1
}

function main {
    # If of each is true we stopped rtorrent. Else we start it )
    if check_live_hosts || check_ssh; then
	$TRANS_REMOTE $DEFAULT_OPT --torrent all --stop
	echo "Stop all torrents $(date)"
    else
	$TRANS_REMOTE $DEFAULT_OPT --torrent all --start
	echo "Start all torrents $(date)"
    fi
}

main
